jobs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from . import views
from . import feeds

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',                     views.JobList.as_view(),     name='job_list'),
    url(r'^new/$',                 views.JobCreate.as_view(),   name='job_create'),
    url(r'^mine/$',                views.MyListings.as_view(),  name='job_list_mine'),
    url(r'^(?P<pk>\d+)/$',         views.JobDetail.as_view(),   name='job_detail'),
    url(r'^(?P<pk>\d+)/edit/$',    views.JobEdit.as_view(),     name='job_edit'),
    url(r'^(?P<pk>\d+)/publish/$', views.PublishJob.as_view(),  name='job_publish'),
    url(r'^(?P<pk>\d+)/archive/$', views.ArchiveJob.as_view(),  name='job_archive'),
    url(r'^(?P<pk>\d+)/flag/$',    views.FlagJob.as_view(),     name='job_flag'),
    url(r'^search/$',              views.SearchView.as_view(),  name='job_search'),
    url(r'^feed/$',                feeds.JobFeed(),             name='job_feed'),
    url(r'^login/$',               views.Login.as_view(),       name='login'),
    url(r'^flags/$',               views.ReviewFlags.as_view(), name='review_flags'),
    url(r'^logout/$',              'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'',        include('social_auth.urls')),
)

jobs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from taggit.managers import TaggableManager


class JobListing(models.Model):
    creator = models.ForeignKey(User, related_name='job_listings')
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    # Job info
    title = models.CharField(max_length=500, help_text='Title of the job - e.g. "Intern", "Software Developer", "CTO", etc.')
    description = models.TextField(help_text='Full job description. Markdown is allowed.')
    compensation = models.CharField(max_length=500, blank=True, help_text='Salary/compensation range (optional)')
    location = models.CharField(max_length=500, help_text='Where is the job located?')
    location_latitude = models.DecimalField(max_digits=9, decimal_places=6,
        null=True, blank=True)
    location_longitude = models.DecimalField(max_digits=9, decimal_places=6,
        null=True, blank=True)
    skills = TaggableManager('Skills', help_text='Desired skills (used for filtering). Separate multiple skills with commas.')

    # Is remote work allowd?
    REMOTE_YES = "yes"
    REMOTE_MAYBE = "maybe"
    REMOTE_NO = "no"
    REMOTE_CHOICES = (
        (REMOTE_YES, "yes"),
        (REMOTE_MAYBE, "negotiable"),
        (REMOTE_NO, "no (on-site only)"),
    )
    remote = models.CharField('Remote work allowed?', max_length=20, choices=REMOTE_CHOICES, default=REMOTE_MAYBE)

    # Company info
    employer_name = models.CharField(max_length=500)
    employer_website = models.URLField(blank=True)

    # Contact info
    contact_name = models.CharField(max_length=200)
    contact_email = models.EmailField(max_length=500,
        help_text="Applicants will use this email to contact you. Your email will be protected by a CAPTCHA.")

    # Statuses: when a post is initially created it'll be draft, only visible
    # to the user who created it. Once they hit "publish" it becomes active.
    # Jobs that are filled or otherwise "done" can be archived by the creator.
    # The "removed" status is for admins to take spam etc.
    STATUS_DRAFT = "draft"
    STATUS_ACTIVE = "active"
    STATUS_ARCHIVED = "archived"
    STATUS_REMOVED = "removed"
    STATUS_CHOICES = (
        (STATUS_DRAFT, "draft"),
        (STATUS_ACTIVE, "active"),
        (STATUS_ARCHIVED, "archived"),
        (STATUS_REMOVED, "removed")
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_DRAFT)

    def __unicode__(self):
        return self.title


class Flag(models.Model):
    job = models.ForeignKey(JobListing, related_name='flags')
    when = models.DateTimeField(default=timezone.now)
    cleared = models.BooleanField(default=False)

jobs/forms.py
from django import forms

from taggit.forms import TagWidget

from .models import JobListing


class JobListingForm(forms.ModelForm):
    class Meta(object):
        model = JobListing
        fields = ['title', 'description', 'skills', 'compensation',
                  'location', 'location_latitude', 'location_longitude',
                  'remote', 'employer_name', 'employer_website',
                  'contact_name', 'contact_email']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input-block-level'}),
            'description': forms.Textarea(attrs={'class': 'input-block-level'}),
            'skills': TagWidget(attrs={'class': 'input-block-level'}),
            'compensation': forms.TextInput(attrs={'class': 'input-block-level'}),
            'location': forms.TextInput(attrs={'class': 'input-block-level'}),
            'location_latitude': forms.HiddenInput(),
            'location_longitude': forms.HiddenInput(),
            'employer_name': forms.TextInput(attrs={'class': 'input-block-level'}),
            'employer_website': forms.TextInput(attrs={'class': 'input-block-level'}),
            'contact_name': forms.TextInput(attrs={'class': 'input-block-level'}),
            'contact_email': forms.TextInput(attrs={'class': 'input-block-level'}),
        }


class SearchForm(forms.Form):
    DISTANCES = (
        ('', '-----------'),
        ('50', '50 km'),
        ('100', '100 km'),
        ('1000', '1000 km'),
    )
    query = forms.CharField(widget=forms.TextInput(attrs={
                'class': 'search-query input-block-level',
                'placeholder': 'Search'}), required=False)
    distance = forms.ChoiceField(choices=DISTANCES, required=False)
    longitude = forms.FloatField(widget=forms.HiddenInput, required=False)
    latitude = forms.FloatField(widget=forms.HiddenInput, required=False)

jobs/views.py
import json

from django.contrib import messages
from django.core import urlresolvers
from django.db.models import Q, Count
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect

from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
from haystack.inputs import Raw
from haystack.query import SearchQuerySet, EmptySearchQuerySet
from haystack.utils.geo import Point, D
from taggit.models import Tag

from .models import JobListing
from .forms import JobListingForm, SearchForm


class JobQuerysetMixin(object):
    """
    Auth'd users see their own postings; everyone else only sees "active" ones.
    """
    def get_queryset(self):
        q = Q(status=JobListing.STATUS_ACTIVE)
        if self.request.user.is_authenticated():
            q |= Q(creator=self.request.user)
        return self.model.objects.filter(q).order_by('-created')


class JobList(JobQuerysetMixin, ListView):
    """
    List of all published jobs.
    """
    model = JobListing
    template_name = "jobs/index.html"
    context_object_name = 'jobs'
    navitem = "all"


class MyListings(LoginRequiredMixin, JobList):
    """
    "My listings" page.
    """
    template_name = "jobs/mine.html"
    navitem = "mine"

    def get_queryset(self):
        return self.request.user.job_listings.all()


class JobDetail(JobQuerysetMixin, DetailView):
    """
    Individual job listing view.
    """
    model = JobListing
    template_name = "jobs/detail.html"
    context_object_name = 'job'

    def get_context_data(self, **kwargs):
        return super(JobDetail, self).get_context_data(
            user_can_edit=(self.object.creator == self.request.user),
            has_flagged='flagged_%s' % self.object.id in self.request.session
        )


class JobEditMixin(object):
    """
    Common helper for job create/edit.

    Provides:
        * success messages
        * redirect to the job detail on success
    """
    model = JobListing
    form_class = JobListingForm

    def get_context_data(self, **kwargs):
        context = super(JobEditMixin, self).get_context_data(**kwargs)
        tags = Tag.objects.all()
        context['json_tags'] = json.dumps([t.name for t in tags])
        return context

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return super(JobEditMixin, self).form_valid(form)

    def get_success_url(self):
        return urlresolvers.reverse("job_detail", args=(self.object.id,))


class JobCreate(LoginRequiredMixin, JobEditMixin, CreateView):
    """
    Create a new job listing.
    """
    template_name = "jobs/edit.html"
    success_message = "Your job listing has been saved as a draft."
    navitem = "new"

    def get_form_kwargs(self):
        kwargs = super(JobCreate, self).get_form_kwargs()
        kwargs['instance'] = JobListing(creator=self.request.user, status=JobListing.STATUS_DRAFT)
        return kwargs


class JobEdit(LoginRequiredMixin, JobEditMixin, UpdateView):
    """
    Edit an existing job.

    Naturally only the person who created a job can edit it again.
    """
    template_name = "jobs/edit.html"
    success_message = "Your job listing has been updated."

    def get_queryset(self):
        return self.request.user.job_listings.all()


class ChangeJobStatus(LoginRequiredMixin, View):
    """
    Abstract class to change a job's status; see the concrete implentations below.
    """
    def post(self, request, pk):
        job = get_object_or_404(request.user.job_listings, pk=pk)
        job.status = self.new_status
        job.save()
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return redirect('job_detail', job.id)


class PublishJob(ChangeJobStatus):
    new_status = JobListing.STATUS_ACTIVE
    success_message = "Your job listing has been published."


class ArchiveJob(ChangeJobStatus):
    new_status = JobListing.STATUS_ARCHIVED
    success_message = "Your job listing has been archived and is no longer public."


class Login(TemplateView):
    template_name = "login.html"
    navitem = "login"


class FlagJob(View):
    """
    Flag a job as spam.

    Has some basic protection against overposting, but for the most part we'll
    just assume that people are good citizens and let flags through.
    """

    def post(self, request, pk):
        jobs = JobListing.objects.filter(status=JobListing.STATUS_ACTIVE)
        job = get_object_or_404(jobs, pk=pk)

        # Flag the job, but only if we've not already recorded a flag from this session.
        if 'flagged_%s' % pk not in request.session:
            job.flags.create()

        messages.add_message(self.request, messages.SUCCESS,
            "Thanks for helping to keep our site spam-free! An adminstrator will review this posting shortly.")
        request.session['flagged_%s' % pk] = True

        return redirect('job_detail', job.id)


class ReviewFlags(LoginRequiredMixin, SuperuserRequiredMixin, TemplateView):
    """
    Review and manage flags.
    """

    template_name = "flags.html"
    navitem = "flags"

    def get_context_data(self, **kwargs):
        return super(ReviewFlags, self).get_context_data(
            flagged_jobs=JobListing.objects.filter(flags__cleared=False).annotate(Count('flags'))
        )

    def post(self, request):
        try:
            job = JobListing.objects.get(id=request.POST['job_id'])
            action = request.POST['action']
        except (KeyError, JobListing.DoesNotExist):
            return redirect('review_flags')

        if action == 'kill':
            job.status = JobListing.STATUS_REMOVED
            job.save()
            job.flags.update(cleared=True)
            messages.add_message(self.request, messages.SUCCESS, "'%s' removed." % job)
            # FIXME: ban the user here?

        elif action == 'keep':
            job.flags.update(cleared=True)
            messages.add_message(self.request, messages.SUCCESS, "'%s' kept." % job)

        return redirect('review_flags')


class SearchView(ListView):
    template_name = "search/search.html"
    navitem = "search"
    paginate_by = 10
    load_all = True

    def get(self, request, *args, **kwargs):
        self.form = SearchForm(self.request.GET or None)
        return super(SearchView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        sqs = SearchQuerySet()
        if 'query' in self.request.GET and self.form.is_valid():
            cleaned_data = self.form.cleaned_data
            if cleaned_data['query']:
                sqs = sqs.filter(content=Raw(cleaned_data['query']))
            if cleaned_data['distance']:
                distance = D(km=int(cleaned_data['distance']))
                point = Point(cleaned_data['longitude'], cleaned_data['latitude'])
                sqs = sqs \
                    .dwithin('location_coordinates', point, distance) \
                    .distance('location_coordinates', point) \
                    .order_by('distance')
        else:
            sqs = EmptySearchQuerySet()
        if self.load_all:
            sqs = sqs.load_all()
        return sqs

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        query_args = self.request.GET.copy()
        query_args.pop('page', None)
        context.update({
            'form': self.form,
            'search': 'query' in self.request.GET,
            'query_args': query_args,
        })
        return context

jobs/templates/jobs/detail.html
{% extends "base.html" %}

{% block content %}
  {% load markup mailhide %}
  {% load url from future %}

  {% if user_can_edit %}
    <div class="well action-well pull-right">
      {% if job.status == 'draft' %}
        <p>This listing is a draft and has not yet been published.</p>
        <form class="form-inline" method="post" action="{% url "job_publish" job.id %}">
          {% csrf_token %}
          <a class="btn btn-block" href="{% url "job_edit" job.id %}">Edit</a>
          <button class="btn btn-block btn-primary">Publish</button>
        </form>
      {% elif job.status == 'active' %}
        <p>This listing is active.</p>
        <form class="form-inline" method="post" action="{% url "job_archive" job.id %}">
          {% csrf_token %}
          <a class="btn btn-block" href="{% url "job_edit" job.id %}">Edit</a>
          <button class="btn btn-block btn-primary">Archive</button>
        </form>
      {% elif job.status == 'archived' %}
        <p>You archived this listing, so it's no longer publically visable.</p>
        <form class="form-inline" method="post" action="{% url "job_publish" job.id %}">
          {% csrf_token %}
          <a class="btn btn-block" href="{% url "job_edit" job.id %}">Edit</a>
          <button class="btn btn-block btn-primary">Re-publish</button>
        </form>
      {% elif job.status == 'removed' %}
        <p class="text-error">This listing has been removed for violating the site's guidlines.</p>
      {% endif %}
    </div>
  {% elif not has_flagged %}
    <div class="pull-right flag">
      <form action="{% url "job_flag" job.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger btn-mini flag">Flag as spam</button>
      </form>
    </div>
  {% endif %}

  {% include "jobs/snippets/title.html" %}
  {{ job.description|markdown:"safe" }}

  <div class="well well-small job-meta">
    <dl class="dl-horizontal">
      <dt>Desired skills:</dt>
      <dd>
        {% for skill in job.skills.all %}
          {{ skill }}{% if not forloop.last %},{% endif %}
        {% endfor %}
      </dd>
      <dt>Location:</dt>
      <dd>{{ job.location }} ({{ job.remote|yesno:"remote OK,on-site only" }})</dd>
      {% if job.compensation %}
        <dt>Compensation:</dt>
        <dd>{{ job.compensation }}</dd>
      {% endif %}
      <dt>Contact:</dt>
      <dd><a href="{{ job.contact_email|mailhide }}" onclick="window.open('{{ job.contact_email|mailhide }}', '', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300'); return false;" title="Reveal this e-mail address">{{ job.contact_name }}</a></dd>
    </dl>
  </div>

{% endblock %}

jobs/templates/jobs/edit.html
{% extends "base.html" %}
{% load static %}

{% block extrahead %}
  {{ block.super }}
  <link href="{% static "select2/select2.css" %}" rel="stylesheet">
  <script src="{% static "jquery-1.9.1.min.js" %}"></script>
  <script src="{% static "select2/select2.min.js" %}"></script>
  <script src="//maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
  <script>
  $(document).ready(function() {
    var location_service = new google.maps.places.AutocompleteService();
    var geocode_service = new google.maps.Geocoder();
    // TODO: Might wanna switch tags to ajax.
    $('#id_skills').select2({
      tags: {{ json_tags|safe }},
      tokenSeparators: [","]
    });
    $('#id_location').select2({
      minimumInputLength: 3,
      query: function(options) {
        location_service.getPlacePredictions({input: options.term, options: {types: ['geocode']}}, function(predictions, status) {
          var results = {more: false};
          if (status != google.maps.places.PlacesServiceStatus.OK) {
            results.results = [];
          } else {
            results.results = predictions;
            results.results = $.map(predictions, function(obj) {
              return {'id': obj.description, 'text': obj.description, gid: obj.id};
            });
          }
          options.callback(results);
        });
      },
      initSelection: function(element, callback) {
        var val = $(element).val();
        if (val) {
          callback({id: val, text:val});
        }
      }
    }).change(function(val) {
      geocode_service.geocode({address: val.val}, function(results, status) {
        console.debug(results);
        if (status == google.maps.GeocoderStatus.OK) {
          var result = results[0].geometry.location;
          $('#id_location_longitude').val(result.lng().toFixed(6));
          $('#id_location_latitude').val(result.lat().toFixed(6));
        }
      });
    });
  });
  </script>
{% endblock extrahead %}

{% block content %}
  {% load bootstrap_tags %}
  <form action="." method="POST" class="form-horizontal">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-primary pull-right" value="Save {% if not form.instance.pk %}&amp; preview {% endif %}">
  </form>
{% endblock %}

jobs/templates/jobs/index.html
{% extends "base.html" %}

{% block content %}
  {% load url from future %}
  {% for job in jobs %}
    <div class="job">
      {% include "jobs/snippets/title.html" %}
      <p>{{ job.description|truncatewords:"100" }}</p>
    </div>
  {% empty %}
    {% block nojobs %}
      <div class="well">
        <h4>There are no active jobs right now. Why not <a href="{% url "job_create" %}">list one yourself</a>?</h4>
      </div>
    {% endblock %}
  {% endfor %}
{% endblock %}

jobs/templates/jobs/mine.html
{% extends "jobs/index.html" %}

{% block nojobs %}
  {% load url from future %}
  <div class="well">
    <h4>You have no job listings. Why not <a href="{% url "job_create" %}">create one</a>?</h4>
  </div>
{% endblock %}